const SET_TOKEN = 'SET_TOKEN';
const RESET_TOKEN = 'RESET_TOKEN';
const SET_LOCATIONS = 'GET_LOCATIONS';
const ADD_LOCATION = 'ADD_LOCATION';
const DELETE_LOCATION = 'DELETE_LOCATION';
const SAVE_SELECTED_LOCATION = 'SAVED_SELECED_LOCATION';

const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';

export {
  SET_TOKEN,
  RESET_TOKEN,
  SET_LOCATIONS,
  ADD_LOCATION,
  DELETE_LOCATION,
  SET_SELECTED_LOCATION,
  SAVE_SELECTED_LOCATION,
};
